services:
  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=securepassword

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - PYTHONUNBUFFERED=1
      - MONGO_USER=admin
      - MONGO_PASSWORD=securepassword
      - MONGO_DATABASE=meteo_cameroun
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true # Ensures hot reload works in Docker
      - REACT_APP_API_URL=http://backend:8000/api

  mobile:
    build: ./mobile
    volumes:
      - ./mobile:/app
    ports:
      - "19000:19000"   # Expo Go (modifie selon ton besoin)
      - "19001:19001"   # Expo LAN
      - "8081:8081"     # Metro bundler (optionnel)
    stdin_open: true
    tty: true
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0

volumes:
  mongo_data: